### PR TITLE
Fix timeout update example plugin

### LINKED ISSUE #10: Add file log handler
Include file handler (probably the rotating version) in logging: https://github.com/nautls/ergomatic/blob/f5739b513273f830b911a4800f3981eabed6e83e/src/log.ts#L13

Will make it easier for users to give us logs in case of errors, etc

Using [`RotatingFileHandler`](https://deno.land/std@0.196.0/log/handlers.ts?source=#L227) requires calling `setup` on the handler, which means we have to move all logger creation in async methods, currently loggers are created in the constructor

### PR DESCRIPTION
**Pull request by ross-weir**
- Fix incompatibility with `axios` timeout config due to missing nodejs api shim, use signals instead
- Make example plugin do something with blockchain client
- Add file logging, added a sync version of rotating log handler, its the same as `RotatingFileHandler` provided by deno std log except uses `*Sync` methods. Closes #10 - it looks like this handler being `async` in deno might be a bug, we should hopefully be able to remove [this handler](https://github.com/nautls/ergomatic/pull/12/files#diff-dafa5ebe0f463a0ac93f64787d8ca777a93d8b37aa8eaecde92c469b86430a06R33) at some point in the future: https://github.com/denoland/deno_std/issues/3538#issuecomment-1676942783

### CODE REVIEW

File: src/log.ts [hunk 1]
```diff
@@ -1,13 +1,26 @@
...
 import { isTesting } from "./_utils.ts";
+import { ErgomaticError } from "./error.ts";
 
 function formatter({ loggerName, levelName, msg }: LogRecord) {
   const datetime = format(new Date(), "yyyy-MM-dd HH:mm:ss");
 
   return `[${datetime}][${loggerName}][${levelName}] ${msg}`;
 }
 
+function _logsDir() {
```
Comment (ross-weir) [inline src/log.ts:14]: this is coming in separate PR (it ended up being a bit more involved), prefixed with `_` for now to silence linter.

File: src/log.ts [hunk 2]
```diff
@@ -1,21 +1,149 @@
...
+
+/**
+ * `RotatingFileHandler` provided by deno has async `setup()` method
+ * Because of this we would need to refactor a lot of code to make it work as
+ * our loggers are currently created in constructors, etc.
+ *
+ * Create a sync version of `RotatingFileHandler` and use that instead.
+ * This is basically just `RotatingFileHandler` but using `Deno.*Sync` methods instead.
+ */
+class SyncRotatingFileHandler extends handlers.FileHandler {
```
Comment (ross-weir) [inline src/log.ts:48]: I hope we'll be able to remove this at some point, `RotatingFileHandler.setup` being async might be a deno issue: https://github.com/denoland/deno_std/issues/3538#issuecomment-1676942783

**Review by arobsn — APPROVED** [review]
